name: dart_kenall
description: Unofficially Kenall API Client.
version: 1.4.0
homepage: https://kenall.jp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.1
  http: ^0.13.5
  meta: ^1.8.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.6
  mockito: ^5.3.2
  build_runner: ^2.3.0

executables:
  kenall-cli: