name: dart_kenall
description: Unofficially Kenall API Client.
version: 1.2.0
homepage: https://kenall.jp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.0
  http: ^0.13.4
  meta: ^1.7.0
  json_serializable: ^6.1.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.20.0
  mockito: ^5.0.16
  build_runner: ^2.1.7

executables:
  kenall-cli: